// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/MsMethod.proto

package com.cm4j.grpc.proto;

public final class MS_METHOD_GRPC {
  private MS_METHOD_GRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MS_METHOD_REQOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 seqId = 1;
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    boolean hasSeqId();
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    long getSeqId();

    // required string className = 2;
    /**
     * <code>required string className = 2;</code>
     *
     * <pre>
     * class名字
     * </pre>
     */
    boolean hasClassName();
    /**
     * <code>required string className = 2;</code>
     *
     * <pre>
     * class名字
     * </pre>
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 2;</code>
     *
     * <pre>
     * class名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    // required string methodName = 3;
    /**
     * <code>required string methodName = 3;</code>
     *
     * <pre>
     * 方法名
     * </pre>
     */
    boolean hasMethodName();
    /**
     * <code>required string methodName = 3;</code>
     *
     * <pre>
     * 方法名
     * </pre>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string methodName = 3;</code>
     *
     * <pre>
     * 方法名
     * </pre>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    // required bytes params = 4;
    /**
     * <code>required bytes params = 4;</code>
     *
     * <pre>
     * 参数信息
     * </pre>
     */
    boolean hasParams();
    /**
     * <code>required bytes params = 4;</code>
     *
     * <pre>
     * 参数信息
     * </pre>
     */
    com.google.protobuf.ByteString getParams();
  }
  /**
   * Protobuf type {@code MS_METHOD_REQ}
   */
  public static final class MS_METHOD_REQ extends
      com.google.protobuf.GeneratedMessage
      implements MS_METHOD_REQOrBuilder {
    // Use MS_METHOD_REQ.newBuilder() to construct.
    private MS_METHOD_REQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MS_METHOD_REQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MS_METHOD_REQ defaultInstance;
    public static MS_METHOD_REQ getDefaultInstance() {
      return defaultInstance;
    }

    public MS_METHOD_REQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MS_METHOD_REQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seqId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              className_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              methodName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              params_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_REQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_REQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.class, com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.Builder.class);
    }

    public static com.google.protobuf.Parser<MS_METHOD_REQ> PARSER =
        new com.google.protobuf.AbstractParser<MS_METHOD_REQ>() {
      public MS_METHOD_REQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MS_METHOD_REQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MS_METHOD_REQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 seqId = 1;
    public static final int SEQID_FIELD_NUMBER = 1;
    private long seqId_;
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    public long getSeqId() {
      return seqId_;
    }

    // required string className = 2;
    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private java.lang.Object className_;
    /**
     * <code>required string className = 2;</code>
     *
     * <pre>
     * class名字
     * </pre>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string className = 2;</code>
     *
     * <pre>
     * class名字
     * </pre>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string className = 2;</code>
     *
     * <pre>
     * class名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string methodName = 3;
    public static final int METHODNAME_FIELD_NUMBER = 3;
    private java.lang.Object methodName_;
    /**
     * <code>required string methodName = 3;</code>
     *
     * <pre>
     * 方法名
     * </pre>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string methodName = 3;</code>
     *
     * <pre>
     * 方法名
     * </pre>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string methodName = 3;</code>
     *
     * <pre>
     * 方法名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes params = 4;
    public static final int PARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>required bytes params = 4;</code>
     *
     * <pre>
     * 参数信息
     * </pre>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes params = 4;</code>
     *
     * <pre>
     * 参数信息
     * </pre>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    private void initFields() {
      seqId_ = 0L;
      className_ = "";
      methodName_ = "";
      params_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClassName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, seqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, params_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, params_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MS_METHOD_REQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_REQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_REQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.class, com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.Builder.class);
      }

      // Construct using com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        seqId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_REQ_descriptor;
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ getDefaultInstanceForType() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.getDefaultInstance();
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ build() {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ buildPartial() {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ result = new com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seqId_ = seqId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.className_ = className_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ) {
          return mergeFrom((com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ other) {
        if (other == com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ.getDefaultInstance()) return this;
        if (other.hasSeqId()) {
          setSeqId(other.getSeqId());
        }
        if (other.hasClassName()) {
          bitField0_ |= 0x00000002;
          className_ = other.className_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000004;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClassName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        if (!hasParams()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_REQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 seqId = 1;
      private long seqId_ ;
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public boolean hasSeqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public long getSeqId() {
        return seqId_;
      }
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public Builder setSeqId(long value) {
        bitField0_ |= 0x00000001;
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public Builder clearSeqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seqId_ = 0L;
        onChanged();
        return this;
      }

      // required string className = 2;
      private java.lang.Object className_ = "";
      /**
       * <code>required string className = 2;</code>
       *
       * <pre>
       * class名字
       * </pre>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string className = 2;</code>
       *
       * <pre>
       * class名字
       * </pre>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string className = 2;</code>
       *
       * <pre>
       * class名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string className = 2;</code>
       *
       * <pre>
       * class名字
       * </pre>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 2;</code>
       *
       * <pre>
       * class名字
       * </pre>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 2;</code>
       *
       * <pre>
       * class名字
       * </pre>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        className_ = value;
        onChanged();
        return this;
      }

      // required string methodName = 3;
      private java.lang.Object methodName_ = "";
      /**
       * <code>required string methodName = 3;</code>
       *
       * <pre>
       * 方法名
       * </pre>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string methodName = 3;</code>
       *
       * <pre>
       * 方法名
       * </pre>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string methodName = 3;</code>
       *
       * <pre>
       * 方法名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string methodName = 3;</code>
       *
       * <pre>
       * 方法名
       * </pre>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 3;</code>
       *
       * <pre>
       * 方法名
       * </pre>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 3;</code>
       *
       * <pre>
       * 方法名
       * </pre>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }

      // required bytes params = 4;
      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes params = 4;</code>
       *
       * <pre>
       * 参数信息
       * </pre>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes params = 4;</code>
       *
       * <pre>
       * 参数信息
       * </pre>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>required bytes params = 4;</code>
       *
       * <pre>
       * 参数信息
       * </pre>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes params = 4;</code>
       *
       * <pre>
       * 参数信息
       * </pre>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000008);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MS_METHOD_REQ)
    }

    static {
      defaultInstance = new MS_METHOD_REQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MS_METHOD_REQ)
  }

  public interface MS_METHOD_RESPOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 seqId = 1;
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    boolean hasSeqId();
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    long getSeqId();

    // optional bytes reback = 2;
    /**
     * <code>optional bytes reback = 2;</code>
     *
     * <pre>
     * 返回信息
     * </pre>
     */
    boolean hasReback();
    /**
     * <code>optional bytes reback = 2;</code>
     *
     * <pre>
     * 返回信息
     * </pre>
     */
    com.google.protobuf.ByteString getReback();

    // optional int32 errorCode = 3;
    /**
     * <code>optional int32 errorCode = 3;</code>
     *
     * <pre>
     * 错误码异常
     * </pre>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 3;</code>
     *
     * <pre>
     * 错误码异常
     * </pre>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code MS_METHOD_RESP}
   */
  public static final class MS_METHOD_RESP extends
      com.google.protobuf.GeneratedMessage
      implements MS_METHOD_RESPOrBuilder {
    // Use MS_METHOD_RESP.newBuilder() to construct.
    private MS_METHOD_RESP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MS_METHOD_RESP(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MS_METHOD_RESP defaultInstance;
    public static MS_METHOD_RESP getDefaultInstance() {
      return defaultInstance;
    }

    public MS_METHOD_RESP getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MS_METHOD_RESP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seqId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reback_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errorCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_RESP_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_RESP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.class, com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.Builder.class);
    }

    public static com.google.protobuf.Parser<MS_METHOD_RESP> PARSER =
        new com.google.protobuf.AbstractParser<MS_METHOD_RESP>() {
      public MS_METHOD_RESP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MS_METHOD_RESP(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MS_METHOD_RESP> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 seqId = 1;
    public static final int SEQID_FIELD_NUMBER = 1;
    private long seqId_;
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 seqId = 1;</code>
     *
     * <pre>
     * 协议唯一ID
     * </pre>
     */
    public long getSeqId() {
      return seqId_;
    }

    // optional bytes reback = 2;
    public static final int REBACK_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString reback_;
    /**
     * <code>optional bytes reback = 2;</code>
     *
     * <pre>
     * 返回信息
     * </pre>
     */
    public boolean hasReback() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes reback = 2;</code>
     *
     * <pre>
     * 返回信息
     * </pre>
     */
    public com.google.protobuf.ByteString getReback() {
      return reback_;
    }

    // optional int32 errorCode = 3;
    public static final int ERRORCODE_FIELD_NUMBER = 3;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 3;</code>
     *
     * <pre>
     * 错误码异常
     * </pre>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errorCode = 3;</code>
     *
     * <pre>
     * 错误码异常
     * </pre>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private void initFields() {
      seqId_ = 0L;
      reback_ = com.google.protobuf.ByteString.EMPTY;
      errorCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, seqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, reback_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errorCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, reback_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errorCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MS_METHOD_RESP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_RESP_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_RESP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.class, com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.Builder.class);
      }

      // Construct using com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        seqId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        reback_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_MS_METHOD_RESP_descriptor;
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP getDefaultInstanceForType() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.getDefaultInstance();
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP build() {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP buildPartial() {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP result = new com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seqId_ = seqId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reback_ = reback_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorCode_ = errorCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP) {
          return mergeFrom((com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP other) {
        if (other == com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP.getDefaultInstance()) return this;
        if (other.hasSeqId()) {
          setSeqId(other.getSeqId());
        }
        if (other.hasReback()) {
          setReback(other.getReback());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cm4j.grpc.proto.MS_METHOD_GRPC.MS_METHOD_RESP) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 seqId = 1;
      private long seqId_ ;
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public boolean hasSeqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public long getSeqId() {
        return seqId_;
      }
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public Builder setSeqId(long value) {
        bitField0_ |= 0x00000001;
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 seqId = 1;</code>
       *
       * <pre>
       * 协议唯一ID
       * </pre>
       */
      public Builder clearSeqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seqId_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes reback = 2;
      private com.google.protobuf.ByteString reback_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reback = 2;</code>
       *
       * <pre>
       * 返回信息
       * </pre>
       */
      public boolean hasReback() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes reback = 2;</code>
       *
       * <pre>
       * 返回信息
       * </pre>
       */
      public com.google.protobuf.ByteString getReback() {
        return reback_;
      }
      /**
       * <code>optional bytes reback = 2;</code>
       *
       * <pre>
       * 返回信息
       * </pre>
       */
      public Builder setReback(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reback = 2;</code>
       *
       * <pre>
       * 返回信息
       * </pre>
       */
      public Builder clearReback() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reback_ = getDefaultInstance().getReback();
        onChanged();
        return this;
      }

      // optional int32 errorCode = 3;
      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 3;</code>
       *
       * <pre>
       * 错误码异常
       * </pre>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errorCode = 3;</code>
       *
       * <pre>
       * 错误码异常
       * </pre>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 3;</code>
       *
       * <pre>
       * 错误码异常
       * </pre>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000004;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 3;</code>
       *
       * <pre>
       * 错误码异常
       * </pre>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MS_METHOD_RESP)
    }

    static {
      defaultInstance = new MS_METHOD_RESP(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MS_METHOD_RESP)
  }

  public interface PRIMITIVE_PARAMOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool paramBool = 1;
    /**
     * <code>optional bool paramBool = 1;</code>
     *
     * <pre>
     * bool值
     * </pre>
     */
    boolean hasParamBool();
    /**
     * <code>optional bool paramBool = 1;</code>
     *
     * <pre>
     * bool值
     * </pre>
     */
    boolean getParamBool();

    // optional int32 paramNumber = 2;
    /**
     * <code>optional int32 paramNumber = 2;</code>
     *
     * <pre>
     * 整型
     * </pre>
     */
    boolean hasParamNumber();
    /**
     * <code>optional int32 paramNumber = 2;</code>
     *
     * <pre>
     * 整型
     * </pre>
     */
    int getParamNumber();

    // optional int64 paramLong = 3;
    /**
     * <code>optional int64 paramLong = 3;</code>
     *
     * <pre>
     * 长整型
     * </pre>
     */
    boolean hasParamLong();
    /**
     * <code>optional int64 paramLong = 3;</code>
     *
     * <pre>
     * 长整型
     * </pre>
     */
    long getParamLong();

    // optional double paramDouble = 4;
    /**
     * <code>optional double paramDouble = 4;</code>
     *
     * <pre>
     * 小数
     * </pre>
     */
    boolean hasParamDouble();
    /**
     * <code>optional double paramDouble = 4;</code>
     *
     * <pre>
     * 小数
     * </pre>
     */
    double getParamDouble();

    // optional string paramString = 5;
    /**
     * <code>optional string paramString = 5;</code>
     *
     * <pre>
     * 字符串
     * </pre>
     */
    boolean hasParamString();
    /**
     * <code>optional string paramString = 5;</code>
     *
     * <pre>
     * 字符串
     * </pre>
     */
    java.lang.String getParamString();
    /**
     * <code>optional string paramString = 5;</code>
     *
     * <pre>
     * 字符串
     * </pre>
     */
    com.google.protobuf.ByteString
        getParamStringBytes();
  }
  /**
   * Protobuf type {@code PRIMITIVE_PARAM}
   */
  public static final class PRIMITIVE_PARAM extends
      com.google.protobuf.GeneratedMessage
      implements PRIMITIVE_PARAMOrBuilder {
    // Use PRIMITIVE_PARAM.newBuilder() to construct.
    private PRIMITIVE_PARAM(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PRIMITIVE_PARAM(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PRIMITIVE_PARAM defaultInstance;
    public static PRIMITIVE_PARAM getDefaultInstance() {
      return defaultInstance;
    }

    public PRIMITIVE_PARAM getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PRIMITIVE_PARAM(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              paramBool_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              paramNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              paramLong_ = input.readInt64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              paramDouble_ = input.readDouble();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              paramString_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_PRIMITIVE_PARAM_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_PRIMITIVE_PARAM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.class, com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.Builder.class);
    }

    public static com.google.protobuf.Parser<PRIMITIVE_PARAM> PARSER =
        new com.google.protobuf.AbstractParser<PRIMITIVE_PARAM>() {
      public PRIMITIVE_PARAM parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PRIMITIVE_PARAM(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PRIMITIVE_PARAM> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool paramBool = 1;
    public static final int PARAMBOOL_FIELD_NUMBER = 1;
    private boolean paramBool_;
    /**
     * <code>optional bool paramBool = 1;</code>
     *
     * <pre>
     * bool值
     * </pre>
     */
    public boolean hasParamBool() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool paramBool = 1;</code>
     *
     * <pre>
     * bool值
     * </pre>
     */
    public boolean getParamBool() {
      return paramBool_;
    }

    // optional int32 paramNumber = 2;
    public static final int PARAMNUMBER_FIELD_NUMBER = 2;
    private int paramNumber_;
    /**
     * <code>optional int32 paramNumber = 2;</code>
     *
     * <pre>
     * 整型
     * </pre>
     */
    public boolean hasParamNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 paramNumber = 2;</code>
     *
     * <pre>
     * 整型
     * </pre>
     */
    public int getParamNumber() {
      return paramNumber_;
    }

    // optional int64 paramLong = 3;
    public static final int PARAMLONG_FIELD_NUMBER = 3;
    private long paramLong_;
    /**
     * <code>optional int64 paramLong = 3;</code>
     *
     * <pre>
     * 长整型
     * </pre>
     */
    public boolean hasParamLong() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 paramLong = 3;</code>
     *
     * <pre>
     * 长整型
     * </pre>
     */
    public long getParamLong() {
      return paramLong_;
    }

    // optional double paramDouble = 4;
    public static final int PARAMDOUBLE_FIELD_NUMBER = 4;
    private double paramDouble_;
    /**
     * <code>optional double paramDouble = 4;</code>
     *
     * <pre>
     * 小数
     * </pre>
     */
    public boolean hasParamDouble() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double paramDouble = 4;</code>
     *
     * <pre>
     * 小数
     * </pre>
     */
    public double getParamDouble() {
      return paramDouble_;
    }

    // optional string paramString = 5;
    public static final int PARAMSTRING_FIELD_NUMBER = 5;
    private java.lang.Object paramString_;
    /**
     * <code>optional string paramString = 5;</code>
     *
     * <pre>
     * 字符串
     * </pre>
     */
    public boolean hasParamString() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string paramString = 5;</code>
     *
     * <pre>
     * 字符串
     * </pre>
     */
    public java.lang.String getParamString() {
      java.lang.Object ref = paramString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paramString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string paramString = 5;</code>
     *
     * <pre>
     * 字符串
     * </pre>
     */
    public com.google.protobuf.ByteString
        getParamStringBytes() {
      java.lang.Object ref = paramString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paramString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      paramBool_ = false;
      paramNumber_ = 0;
      paramLong_ = 0L;
      paramDouble_ = 0D;
      paramString_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, paramBool_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, paramNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, paramLong_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, paramDouble_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getParamStringBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, paramBool_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, paramNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, paramLong_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, paramDouble_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getParamStringBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PRIMITIVE_PARAM}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAMOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_PRIMITIVE_PARAM_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_PRIMITIVE_PARAM_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.class, com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.Builder.class);
      }

      // Construct using com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        paramBool_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        paramNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        paramLong_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        paramDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        paramString_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.internal_static_PRIMITIVE_PARAM_descriptor;
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM getDefaultInstanceForType() {
        return com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.getDefaultInstance();
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM build() {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM buildPartial() {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM result = new com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.paramBool_ = paramBool_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.paramNumber_ = paramNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.paramLong_ = paramLong_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.paramDouble_ = paramDouble_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.paramString_ = paramString_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM) {
          return mergeFrom((com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM other) {
        if (other == com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM.getDefaultInstance()) return this;
        if (other.hasParamBool()) {
          setParamBool(other.getParamBool());
        }
        if (other.hasParamNumber()) {
          setParamNumber(other.getParamNumber());
        }
        if (other.hasParamLong()) {
          setParamLong(other.getParamLong());
        }
        if (other.hasParamDouble()) {
          setParamDouble(other.getParamDouble());
        }
        if (other.hasParamString()) {
          bitField0_ |= 0x00000010;
          paramString_ = other.paramString_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cm4j.grpc.proto.MS_METHOD_GRPC.PRIMITIVE_PARAM) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool paramBool = 1;
      private boolean paramBool_ ;
      /**
       * <code>optional bool paramBool = 1;</code>
       *
       * <pre>
       * bool值
       * </pre>
       */
      public boolean hasParamBool() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool paramBool = 1;</code>
       *
       * <pre>
       * bool值
       * </pre>
       */
      public boolean getParamBool() {
        return paramBool_;
      }
      /**
       * <code>optional bool paramBool = 1;</code>
       *
       * <pre>
       * bool值
       * </pre>
       */
      public Builder setParamBool(boolean value) {
        bitField0_ |= 0x00000001;
        paramBool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool paramBool = 1;</code>
       *
       * <pre>
       * bool值
       * </pre>
       */
      public Builder clearParamBool() {
        bitField0_ = (bitField0_ & ~0x00000001);
        paramBool_ = false;
        onChanged();
        return this;
      }

      // optional int32 paramNumber = 2;
      private int paramNumber_ ;
      /**
       * <code>optional int32 paramNumber = 2;</code>
       *
       * <pre>
       * 整型
       * </pre>
       */
      public boolean hasParamNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 paramNumber = 2;</code>
       *
       * <pre>
       * 整型
       * </pre>
       */
      public int getParamNumber() {
        return paramNumber_;
      }
      /**
       * <code>optional int32 paramNumber = 2;</code>
       *
       * <pre>
       * 整型
       * </pre>
       */
      public Builder setParamNumber(int value) {
        bitField0_ |= 0x00000002;
        paramNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 paramNumber = 2;</code>
       *
       * <pre>
       * 整型
       * </pre>
       */
      public Builder clearParamNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        paramNumber_ = 0;
        onChanged();
        return this;
      }

      // optional int64 paramLong = 3;
      private long paramLong_ ;
      /**
       * <code>optional int64 paramLong = 3;</code>
       *
       * <pre>
       * 长整型
       * </pre>
       */
      public boolean hasParamLong() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 paramLong = 3;</code>
       *
       * <pre>
       * 长整型
       * </pre>
       */
      public long getParamLong() {
        return paramLong_;
      }
      /**
       * <code>optional int64 paramLong = 3;</code>
       *
       * <pre>
       * 长整型
       * </pre>
       */
      public Builder setParamLong(long value) {
        bitField0_ |= 0x00000004;
        paramLong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 paramLong = 3;</code>
       *
       * <pre>
       * 长整型
       * </pre>
       */
      public Builder clearParamLong() {
        bitField0_ = (bitField0_ & ~0x00000004);
        paramLong_ = 0L;
        onChanged();
        return this;
      }

      // optional double paramDouble = 4;
      private double paramDouble_ ;
      /**
       * <code>optional double paramDouble = 4;</code>
       *
       * <pre>
       * 小数
       * </pre>
       */
      public boolean hasParamDouble() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double paramDouble = 4;</code>
       *
       * <pre>
       * 小数
       * </pre>
       */
      public double getParamDouble() {
        return paramDouble_;
      }
      /**
       * <code>optional double paramDouble = 4;</code>
       *
       * <pre>
       * 小数
       * </pre>
       */
      public Builder setParamDouble(double value) {
        bitField0_ |= 0x00000008;
        paramDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double paramDouble = 4;</code>
       *
       * <pre>
       * 小数
       * </pre>
       */
      public Builder clearParamDouble() {
        bitField0_ = (bitField0_ & ~0x00000008);
        paramDouble_ = 0D;
        onChanged();
        return this;
      }

      // optional string paramString = 5;
      private java.lang.Object paramString_ = "";
      /**
       * <code>optional string paramString = 5;</code>
       *
       * <pre>
       * 字符串
       * </pre>
       */
      public boolean hasParamString() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string paramString = 5;</code>
       *
       * <pre>
       * 字符串
       * </pre>
       */
      public java.lang.String getParamString() {
        java.lang.Object ref = paramString_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          paramString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string paramString = 5;</code>
       *
       * <pre>
       * 字符串
       * </pre>
       */
      public com.google.protobuf.ByteString
          getParamStringBytes() {
        java.lang.Object ref = paramString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paramString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string paramString = 5;</code>
       *
       * <pre>
       * 字符串
       * </pre>
       */
      public Builder setParamString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        paramString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string paramString = 5;</code>
       *
       * <pre>
       * 字符串
       * </pre>
       */
      public Builder clearParamString() {
        bitField0_ = (bitField0_ & ~0x00000010);
        paramString_ = getDefaultInstance().getParamString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string paramString = 5;</code>
       *
       * <pre>
       * 字符串
       * </pre>
       */
      public Builder setParamStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        paramString_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PRIMITIVE_PARAM)
    }

    static {
      defaultInstance = new PRIMITIVE_PARAM(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PRIMITIVE_PARAM)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MS_METHOD_REQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MS_METHOD_REQ_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MS_METHOD_RESP_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MS_METHOD_RESP_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PRIMITIVE_PARAM_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PRIMITIVE_PARAM_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023grpc/MsMethod.proto\"U\n\rMS_METHOD_REQ\022\r" +
      "\n\005seqId\030\001 \001(\003\022\021\n\tclassName\030\002 \002(\t\022\022\n\nmeth" +
      "odName\030\003 \002(\t\022\016\n\006params\030\004 \002(\014\"B\n\016MS_METHO" +
      "D_RESP\022\r\n\005seqId\030\001 \001(\003\022\016\n\006reback\030\002 \001(\014\022\021\n" +
      "\terrorCode\030\003 \001(\005\"v\n\017PRIMITIVE_PARAM\022\021\n\tp" +
      "aramBool\030\001 \001(\010\022\023\n\013paramNumber\030\002 \001(\005\022\021\n\tp" +
      "aramLong\030\003 \001(\003\022\023\n\013paramDouble\030\004 \001(\001\022\023\n\013p" +
      "aramString\030\005 \001(\t2=\n\017MsMethodService\022*\n\007i" +
      "nvoker\022\016.MS_METHOD_REQ\032\017.MS_METHOD_RESPB" +
      "%\n\023com.cm4j.grpc.protoB\016MS_METHOD_GRPC"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MS_METHOD_REQ_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MS_METHOD_REQ_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MS_METHOD_REQ_descriptor,
              new java.lang.String[] { "SeqId", "ClassName", "MethodName", "Params", });
          internal_static_MS_METHOD_RESP_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MS_METHOD_RESP_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MS_METHOD_RESP_descriptor,
              new java.lang.String[] { "SeqId", "Reback", "ErrorCode", });
          internal_static_PRIMITIVE_PARAM_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PRIMITIVE_PARAM_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PRIMITIVE_PARAM_descriptor,
              new java.lang.String[] { "ParamBool", "ParamNumber", "ParamLong", "ParamDouble", "ParamString", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
